---
kind: pipeline
name: build-linux-arm

platform:
  os: linux
  arch: arm

steps:
- name: dryrun
  image: plugins/docker:linux-arm
  settings:
    build_args:
    - BUILD_VERSION=${DRONE_TAG%-*}
    dockerfile: ./Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: ${DRONE_REPO}
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/pull/**

- name: tags
  image: alpine
  commands:
  - export BASE=${DRONE_TAG:-latest}
  - export TAG=$${BASE##v}
  - if [ "$$TAG" == "latest" ]; then echo -n "latest" > .tags; else echo -n "latest,$${TAG},$${TAG%-*},$${TAG%.*},$${TAG%%.*}" > .tags; fi
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

- name: publish
  image: plugins/docker:linux-arm
  settings:
    build_args:
    - BUILD_VERSION=linux-arm-${DRONE_TAG%-*}
    repo: jamu85/${DRONE_REPO_NAME}
    dockerfile: ./Dockerfile
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

---
kind: pipeline
name: build-linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: dryrun
  image: plugins/docker:linux-arm64
  settings:
    build_args:
    - BUILD_VERSION=${DRONE_TAG%-*}
    dockerfile: ./Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: ${DRONE_REPO}
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/pull/**

- name: tags
  image: alpine
  commands:
  - export BASE=${DRONE_TAG:-latest}
  - export TAG=$${BASE##v}
  - if [ "$$TAG" == "latest" ]; then echo -n "latest" > .tags; else echo -n "latest,$${TAG},$${TAG%-*},$${TAG%.*},$${TAG%%.*}" > .tags; fi
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

- name: publish
  image: plugins/docker:linux-arm64
  settings:
    build_args:
    - BUILD_VERSION=linux-arm64-${DRONE_TAG%-*}
    repo: jamu85/${DRONE_REPO_NAME}
    dockerfile: ./Dockerfile
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

---
kind: pipeline
name: publish-readme

steps:
- name: readme
  image: sheogorath/readme-to-dockerhub
  environment:
    DOCKERHUB_PASSWORD:
      from_secret: docker_password
    DOCKERHUB_REPO_NAME: ${DRONE_REPO_NAME}
    DOCKERHUB_REPO_PREFIX: jamu85
    DOCKERHUB_USERNAME:
      from_secret: docker_username
    README_PATH: README.md
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**